(() => {
'use strict';
const STORE='kopeyka-new-v4';
const defaults={version:5,balance:0,income:[],expenses:[],debts:[],reserves:[],notes:[],settings:{dayPay:4800,nightPay:4800,anchor:'2026-08-17'}};
const $=s=>document.querySelector(s), num=v=>Number(v)||0, money=v=>`${Math.round(num(v)).toLocaleString('ru-RU')} ₽`, today=()=>new Date().toISOString().slice(0,10), uid=()=>crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone=x=>JSON.parse(JSON.stringify(x));
function normalize(x){return {...clone(defaults),...x,income:Array.isArray(x.income)?x.income:[],expenses:Array.isArray(x.expenses)?x.expenses:[],debts:Array.isArray(x.debts)?x.debts:[],reserves:Array.isArray(x.reserves)?x.reserves:[],notes:Array.isArray(x.notes)?x.notes:[],settings:{...defaults.settings,...(x.settings||{})}}}
function load(){try{return normalize(JSON.parse(localStorage.getItem(STORE))||defaults)}catch{return clone(defaults)}}
let state=load(),screen='home',month=new Date();
function save(){localStorage.setItem(STORE,JSON.stringify(state));document.title=`Копейка · ${money(totals().cash)}`}
function totals(){const income=state.income.filter(x=>x.status!=='planned').reduce((a,x)=>a+num(x.amount),0),planned=state.income.filter(x=>x.status==='planned').reduce((a,x)=>a+num(x.amount),0),expense=state.expenses.reduce((a,x)=>a+num(x.amount),0),debt=state.debts.reduce((a,x)=>a+Math.max(0,num(x.amount)-num(x.paid)),0),saved=state.reserves.reduce((a,x)=>a+num(x.saved),0),target=state.reserves.reduce((a,x)=>a+num(x.target),0);return{income,planned,expense,debt,saved,target,cash:num(state.balance)+income-expense,after:num(state.balance)+income-expense-debt-Math.max(0,target-saved)}}
const nav=[['home','⌂','Главная'],['income','₽','Доходы'],['expenses','−','Расходы'],['debts','↗','Долги'],['reserves','◎','Резервы'],['calendar','▦','Календарь'],['notes','✎','Заметки']];
function shell(){return `<header><div class="brand"><span class="logo">₽</span><b>Копейка</b></div><div class="header-actions"><button class="icon-btn" data-act="export">⇩</button><button class="icon-btn" data-act="import">⇧</button></div></header><div class="wrap"><nav class="desktop-nav">${nav.map(n=>`<button class="nav ${screen===n[0]?'active':''}" data-screen="${n[0]}">${n[2]}</button>`).join('')}</nav><main id="main"></main></div><button class="fab" data-act="menu" aria-label="Добавить">+</button><div class="fab-menu" id="fabMenu"><button data-act="income">＋ Доход</button><button data-act="expense">− Расход</button><button data-act="reserve">◎ Резерв</button><button data-act="debt">↗ Долг</button></div><nav class="bottom-nav">${nav.slice(0,5).map(n=>`<button class="${screen===n[0]?'active':''}" data-screen="${n[0]}"><strong>${n[1]}</strong><span>${n[2]}</span></button>`).join('')}</nav><div id="modal"></div><input id="importFile" type="file" accept="application/json" hidden>`}
function render(){document.body.innerHTML=shell();({home,income,expenses,debts,reserves,calendar,notes}[screen]||home)();bind();save()}
function bind(){document.querySelectorAll('[data-screen]').forEach(b=>b.addEventListener('click',()=>{screen=b.dataset.screen;render()}));document.querySelectorAll('[data-act]').forEach(b=>b.addEventListener('click',()=>act(b.dataset.act)));document.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>{const [type,id]=b.dataset.edit.split(':');const map={income:'income',expense:'expenses',debt:'debts',reserve:'reserves'};const x=state[map[type]]?.find(v=>v.id===id);if(type==='income')openIncome(x);if(type==='expense')openExpense(x);if(type==='debt')openDebt(x);if(type==='reserve')openReserve(x)}));document.querySelectorAll('[data-month]').forEach(b=>b.addEventListener('click',()=>{month.setMonth(month.getMonth()+Number(b.dataset.month));render()}));document.querySelectorAll('[data-note-del]').forEach(b=>b.addEventListener('click',()=>{state.notes=state.notes.filter(x=>x.id!==b.dataset.noteDel);save();render()}));const fi=$('#importFile');if(fi)fi.addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader;r.onload=()=>{try{state=normalize(JSON.parse(r.result));save();render()}catch{alert('Файл резервной копии повреждён')}};r.readAsText(f)});}
function act(a){if(a==='menu'){$('#fabMenu')?.classList.toggle('open');return}$('#fabMenu')?.classList.remove('open');if(a==='income')openIncome();if(a==='expense')openExpense();if(a==='reserve')openReserve();if(a==='debt')openDebt();if(a==='note'){const text=$('#newNote')?.value.trim();if(text){state.notes.push({id:uid(),text,date:new Date().toLocaleString('ru-RU')});save();render()}}if(a==='export'){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),ael=document.createElement('a');ael.href=url;ael.download='kopeyka-backup.json';ael.click();setTimeout(()=>URL.revokeObjectURL(url),500)}if(a==='import')$('#importFile')?.click()}
function card(label,value,sub,cls=''){return `<div class="card metric"><small>${label}</small><strong class="${cls}">${value}</strong><span>${sub}</span></div>`}
function row(x,extra=''){const inc=x.type==='income';return `<div class="row"><div class="row-icon">${inc?'₽':x.type==='expense'?'−':x.type==='debt'?'↗':'◎'}</div><div class="grow"><b>${esc(x.title||x.name)}</b><small>${esc(x.date||x.dueDate||'')}</small></div><strong class="${inc?'green':'red'}">${inc?'+':'−'}${money(x.amount)}</strong>${extra}</div>`}
function home(){const t=totals(),ops=[...state.income.map(x=>({...x,type:'income'})),...state.expenses.map(x=>({...x,type:'expense'}))].sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,7);$('#main').innerHTML=`<section class="hero-head"><div><h1>Главная</h1><p>Финансы, смены и цели в одном месте</p></div><div class="actions"><button class="btn" data-act="expense">− Расход</button><button class="btn primary" data-act="income">＋ Доход</button></div></section><section class="hero"><small>Свободно сейчас</small><div class="hero-number ${t.cash<0?'red':''}">${money(t.cash)}</div><p>Фактический остаток по введённым операциям</p></section><section class="grid">${card('Доходы',money(t.income),'получено','green')}${card('Расходы',money(t.expense),'учтено','red')}${card('Долги',money(t.debt),'осталось','red')}${card('Резервы',money(t.saved),'накоплено','green')}</section><section class="grid two"><div class="card"><small>Финансовая подушка</small><strong>${money(t.saved)}</strong><div class="bar"><i style="width:${t.target?Math.min(100,t.saved/t.target*100):0}%"></i></div><span>${t.target?Math.round(t.saved/t.target*100):0}% цели</span></div><div class="card"><small>После обязательств</small><strong class="${t.after<0?'red':'green'}">${money(t.after)}</strong><span>с учётом долгов и незакрытых целей</span></div></section><h3>Быстрые действия</h3><section class="card actions big-actions"><button class="btn primary" data-act="income">＋ Доход</button><button class="btn" data-act="expense">− Расход</button><button class="btn" data-act="reserve">◎ Резерв</button><button class="btn" data-act="debt">↗ Долг</button></section><h3>Последние операции</h3><section class="card">${ops.length?ops.map(row).join(''):'<div class="empty">Операций пока нет</div>'}</section>`}
function income(){const t=totals();$('#main').innerHTML=`<section class="hero-head"><div><h1>Доходы</h1><p>Фактические и планируемые поступления</p></div><button class="btn primary" data-act="income">＋ Добавить</button></section><section class="grid two">${card('Получено',money(t.income),'факт','green')}${card('Планируется',money(t.planned),'ожидается')}</section><section class="card">${state.income.length?state.income.slice().reverse().map(x=>row({...x,type:'income'},`<button class="mini" data-edit="income:${x.id}">⋮</button>`)).join(''):'<div class="empty">Доходов пока нет</div>'}</section>`}
function expenses(){const t=totals();$('#main').innerHTML=`<section class="hero-head"><div><h1>Расходы</h1><p>Контроль трат без двойного учёта</p></div><button class="btn primary" data-act="expense">＋ Добавить</button></section><section class="grid two">${card('Всего расходов',money(t.expense),'учтено','red')}${card('Свободно',money(t.cash),'остаток',t.cash<0?'red':'green')}</section><section class="card">${state.expenses.length?state.expenses.slice().reverse().map(x=>row({...x,type:'expense'},`<button class="mini" data-edit="expense:${x.id}">⋮</button>`)).join(''):'<div class="empty">Расходов пока нет</div>'}</section>`}
function debts(){const t=totals();$('#main').innerHTML=`<section class="hero-head"><div><h1>Долги</h1><p>Обязательства и выплаты</p></div><button class="btn primary" data-act="debt">＋ Добавить</button></section><section class="grid two">${card('Осталось',money(t.debt),'к выплате','red')}${card('Долгов',state.debts.length,'активных')}</section><section class="card">${state.debts.length?state.debts.map(d=>`<div class="row"><div class="row-icon">↗</div><div class="grow"><b>${esc(d.name)}</b><small>до ${esc(d.dueDate||'не указан')} · выплачено ${money(d.paid)}</small></div><strong class="red">${money(Math.max(0,num(d.amount)-num(d.paid)))}</strong><button class="mini" data-edit="debt:${d.id}">⋮</button></div>`).join(''):'<div class="empty">Долгов пока нет</div>'}</section>`}
function reserves(){const t=totals();$('#main').innerHTML=`<section class="hero-head"><div><h1>Резервы</h1><p>Подушка безопасности и финансовые цели</p></div><button class="btn primary" data-act="reserve">＋ Создать</button></section><section class="grid two">${card('Накоплено',money(t.saved),'во всех резервах','green')}${card('Цель',money(t.target),'общая цель')}</section>${state.reserves.length?state.reserves.map(r=>`<section class="card"><div class="reserve-top"><div><b>${esc(r.name)}</b><small>${money(r.saved)} из ${money(r.target)}</small></div><button class="mini" data-edit="reserve:${r.id}">⋮</button></div><div class="bar"><i style="width:${r.target?Math.min(100,r.saved/r.target*100):0}%"></i></div></section>`).join(''):'<section class="card empty">Создай первую финансовую цель</section>'}`}
function shift(date){const a=new Date(state.settings.anchor+'T12:00:00'),b=new Date(date+'T12:00:00'),d=Math.round((b-a)/86400000),i=((d%6)+6)%6;return['day','day','night','night','off','off'][i]}
function calendar(){const y=month.getFullYear(),m=month.getMonth(),days=new Date(y,m+1,0).getDate(),name=month.toLocaleDateString('ru-RU',{month:'long',year:'numeric'});let h=`<section class="hero-head"><div><h1>Календарь</h1><p>${name} · 2 дня / 2 ночи / 2 выходных</p></div><div class="actions"><button class="btn" data-month="-1">‹</button><button class="btn" data-month="1">›</button></div></section><section class="card calendar">`;for(let d=1;d<=days;d++){const iso=new Date(y,m,d).toISOString().slice(0,10),s=shift(iso),pay=s==='day'?num(state.settings.dayPay):s==='night'?num(state.settings.nightPay):0;h+=`<div class="day"><b>${d}</b><span class="shift ${s}">${s==='day'?'ДЕНЬ':s==='night'?'НОЧЬ':'ВЫХОДНОЙ'}</span>${pay?`<em>+${money(pay)}</em>`:''}</div>`}$('#main').innerHTML=h+'</section>'}
function notes(){$('#main').innerHTML=`<section class="hero-head"><div><h1>Заметки</h1><p>Личные записи приложения</p></div></section><section class="card"><textarea id="newNote" rows="4" placeholder="Напиши заметку..."></textarea><button class="btn primary" data-act="note" style="margin-top:10px">Сохранить</button></section><h3>Записи</h3>${state.notes.slice().reverse().map(n=>`<section class="card"><div>${esc(n.text)}</div><small>${esc(n.date)}</small><button class="mini" data-note-del="${n.id}" style="margin-top:10px">Удалить</button></section>`).join('')||'<section class="card empty">Заметок пока нет</section>'}`}
function modal(title,body,action,del=''){const delBtn=del?`<button type="button" class="btn danger" data-delete="${del}">Удалить</button>`:'';$('#modal').innerHTML=`<div class="modal-bg" data-modal-bg><form class="modal" id="activeForm"><div class="modal-title"><b>${title}</b><button type="button" class="mini" data-close>×</button></div>${body}<div class="modal-actions">${delBtn}<button type="button" class="btn" data-close>Отмена</button><button class="btn primary" type="submit">Сохранить</button></div></form></div>`;$('#activeForm').addEventListener('submit',e=>{e.preventDefault();action()});document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',closeModal));$('.modal-bg').addEventListener('click',e=>{if(e.target.classList.contains('modal-bg'))closeModal()});const delEl=$('[data-delete]');if(delEl)delEl.addEventListener('click',()=>{deleteItem(del);closeModal();render()});document.addEventListener('keydown',escKey,{once:true})}
function escKey(e){if(e.key==='Escape')closeModal()}
function closeModal(){$('#modal').innerHTML='';document.querySelectorAll('[data-act]').forEach(()=>{})}
const field=(label,id,type='text',value='',placeholder='')=>`<label class="field">${label}<input id="${id}" type="${type}" value="${esc(value)}" placeholder="${esc(placeholder)}" ${type==='number'?'inputmode="decimal"':''}></label>`;
function openIncome(x=null){modal(x?'Изменить доход':'Новый доход',field('Название','fTitle','text',x?.title,'Зарплата, подработка...')+field('Сумма','fAmount','number',x?.amount)+field('Дата','fDate','date',x?.date||today())+`<label class="field">Статус<select id="fStatus"><option value="actual" ${x?.status!=='planned'?'selected':''}>Получено</option><option value="planned" ${x?.status==='planned'?'selected':''}>Планируется</option></select></label>`,()=>{const z={id:x?.id||uid(),title:$('#fTitle').value.trim()||'Доход',amount:num($('#fAmount').value),date:$('#fDate').value,status:$('#fStatus').value};if(!z.amount)return;const i=state.income.findIndex(a=>a.id===z.id);i<0?state.income.push(z):state.income[i]=z;save();closeModal();render()},x?'income:'+x.id:'')}
function openExpense(x=null){modal(x?'Изменить расход':'Новый расход',field('Название','fTitle','text',x?.title,'Продукты, транспорт...')+field('Сумма','fAmount','number',x?.amount)+field('Дата','fDate',x?.date||today())+`<label class="check"><input id="fMandatory" type="checkbox" ${x?.mandatory?'checked':''}> Обязательный расход</label>`,()=>{const z={id:x?.id||uid(),title:$('#fTitle').value.trim()||'Расход',amount:num($('#fAmount').value),date:$('#fDate').value,mandatory:$('#fMandatory').checked};if(!z.amount)return;const i=state.expenses.findIndex(a=>a.id===z.id);i<0?state.expenses.push(z):state.expenses[i]=z;save();closeModal();render()},x?'expense:'+x.id:'')}
function openDebt(x=null){modal(x?'Изменить долг':'Новый долг',field('Кому / за что','fName','text',x?.name)+field('Сумма','fAmount','number',x?.amount)+field('Уже выплачено','fPaid','number',x?.paid||0)+field('Срок','fDate','date',x?.dueDate||today()),()=>{const z={id:x?.id||uid(),name:$('#fName').value.trim()||'Долг',amount:num($('#fAmount').value),paid:num($('#fPaid').value),dueDate:$('#fDate').value};if(!z.amount)return;const i=state.debts.findIndex(a=>a.id===z.id);i<0?state.debts.push(z):state.debts[i]=z;save();closeModal();render()},x?'debt:'+x.id:'')}
function openReserve(x=null){modal(x?'Изменить резерв':'Новый резерв',field('Название цели','fName','text',x?.name,'Подушка безопасности')+field('Цель','fTarget','number',x?.target)+field('Уже накоплено','fSaved','number',x?.saved||0),()=>{const z={id:x?.id||uid(),name:$('#fName').value.trim()||'Резерв',target:num($('#fTarget').value),saved:num($('#fSaved').value)};if(!z.target)return;const i=state.reserves.findIndex(a=>a.id===z.id);i<0?state.reserves.push(z):state.reserves[i]=z;save();closeModal();render()},x?'reserve:'+x.id:'')}
function deleteItem(key){const [type,id]=key.split(':');const map={income:'income',expense:'expenses',debt:'debts',reserve:'reserves'};if(map[type])state[map[type]]=state[map[type]].filter(x=>x.id!==id);save()}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='kopeyka-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
function importData(){document.getElementById('importFile')?.click()}
function boot(){render()}
boot();
})();