(() => {
'use strict';
const STORE='kopeyka-new-v3';
const defaults={version:3,balance:0,income:[],expenses:[],debts:[],reserves:[],notes:[],settings:{dayPay:4800,nightPay:4800,anchor:'2026-08-17'}};
const $=s=>document.querySelector(s), money=v=>`${Math.round(Number(v)||0).toLocaleString('ru-RU')} ₽`, num=v=>Number(v)||0, id=()=>crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2), today=()=>new Date().toISOString().slice(0,10);
let state=load(), screen='home', month=new Date();
function clone(x){return JSON.parse(JSON.stringify(x))} function load(){try{return normalize(JSON.parse(localStorage.getItem(STORE))||defaults)}catch{return clone(defaults)}}
function normalize(x){return {...clone(defaults),...x,income:Array.isArray(x.income)?x.income:[],expenses:Array.isArray(x.expenses)?x.expenses:[],debts:Array.isArray(x.debts)?x.debts:[],reserves:Array.isArray(x.reserves)?x.reserves:[],notes:Array.isArray(x.notes)?x.notes:[],settings:{...defaults.settings,...(x.settings||{})}}}
function save(){localStorage.setItem(STORE,JSON.stringify(state));updateStats()}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function totals(){const income=state.income.filter(x=>x.status!=='planned').reduce((a,x)=>a+num(x.amount),0), planned=state.income.filter(x=>x.status==='planned').reduce((a,x)=>a+num(x.amount),0), expense=state.expenses.reduce((a,x)=>a+num(x.amount),0), debt=state.debts.reduce((a,x)=>a+Math.max(0,num(x.amount)-num(x.paid)),0), saved=state.reserves.reduce((a,x)=>a+num(x.saved),0), target=state.reserves.reduce((a,x)=>a+num(x.target),0);return{income,planned,expense,debt,saved,target,cash:num(state.balance)+income-expense,after:num(state.balance)+income-expense-debt-(target-saved)}}
function updateStats(){const t=totals();document.title=`Копейка · ${money(t.cash)}`}
const nav=[['home','⌂','Главная'],['income','₽','Доходы'],['expenses','−','Расходы'],['reserves','◎','Резервы'],['calendar','▦','Календарь'],['notes','✎','Заметки']];
function shell(){return `<header><div class="brand"><span class="logo">₽</span><b>Копейка</b></div><div class="header-actions"><button class="icon-btn" data-act="export">⇩</button><button class="icon-btn" data-act="import">⇧</button></div></header><div class="wrap"><nav class="desktop-nav">${nav.map(n=>`<button class="nav ${screen===n[0]?'active':''}" data-screen="${n[0]}">${n[2]}</button>`).join('')}</nav><main id="main"></main></div><button class="fab" data-act="menu">+</button><div class="fab-menu" id="fabMenu"><button data-act="income">＋ Доход</button><button data-act="expense">− Расход</button><button data-act="reserve">◎ Резерв</button><button data-act="debt">↗ Долг</button></div><nav class="bottom-nav">${nav.slice(0,5).map(n=>`<button class="${screen===n[0]?'active':''}" data-screen="${n[0]}"><strong>${n[1]}</strong><span>${n[2]}</span></button>`).join('')}</nav><div id="modal"></div><input id="importFile" type="file" accept="application/json" hidden>`}
function render(){document.body.innerHTML=shell(); if(screen==='home')home();if(screen==='income')income();if(screen==='expenses')expenses();if(screen==='reserves')reserves();if(screen==='calendar')calendar();if(screen==='notes')notes();bind();updateStats()}
function card(label,value,sub,cls=''){return `<div class="card metric"><small>${label}</small><strong class="${cls}">${value}</strong><span>${sub}</span></div>`}
function home(){const t=totals(), ops=[...state.income.map(x=>({...x,type:'income'})),...state.expenses.map(x=>({...x,type:'expense'}))].sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,6);$('#main').innerHTML=`<section class="hero-head"><div><h1>Главная</h1><p>Финансы, смены и цели в одном месте</p></div><div class="actions"><button class="btn" data-act="expense">− Расход</button><button class="btn primary" data-act="income">＋ Доход</button></div></section><section class="hero"><small>Свободно сейчас</small><div class="hero-number ${t.cash<0?'red':''}">${money(t.cash)}</div><p>Фактический остаток по введённым операциям</p></section><section class="grid">${card('Доходы',money(t.income),'получено','green')}${card('Расходы',money(t.expense),'учтено','red')}${card('Долги',money(t.debt),'осталось','red')}${card('Резервы',money(t.saved),'накоплено','green')}</section><section class="grid two"><div class="card"><small>Финансовая подушка</small><strong>${money(t.saved)}</strong><div class="bar"><i style="width:${t.target?Math.min(100,t.saved/t.target*100):0}%"></i></div><span>${t.target?Math.round(t.saved/t.target*100):0}% цели</span></div><div class="card"><small>После обязательств</small><strong class="${t.after<0?'red':'green'}">${money(t.after)}</strong><span>с учётом долгов и незакрытых целей</span></div></section><h3>Быстрые действия</h3><section class="card actions big-actions"><button class="btn primary" data-act="income">＋ Доход</button><button class="btn" data-act="expense">− Расход</button><button class="btn" data-act="reserve">◎ Резерв</button><button class="btn" data-act="debt">↗ Долг</button></section><h3>Последние операции</h3><section class="card">${ops.length?ops.map(op=>row(op)).join(''):'<div class="empty">Операций пока нет</div>'}</section>`}
function row(x,extra=''){return `<div class="row"><div class="row-icon">${x.type==='income'?'₽':x.type==='expense'?'−':x.type==='debt'?'↗':'◎'}</div><div class="grow"><b>${esc(x.title||x.name)}</b><small>${esc(x.date||x.dueDate||'')}</small></div><strong class="${x.type==='income'?'green':'red'}">${x.type==='income'?'+':'−'}${money(x.amount)}</strong>${extra}</div>`}
function income(){const t=totals();$('#main').innerHTML=`<section class="hero-head"><div><h1>Доходы</h1><p>Фактические и планируемые поступления</p></div><button class="btn primary" data-act="income">＋ Добавить</button></section><section class="grid two">${card('Получено',money(t.income),'факт','green')}${card('Планируется',money(t.planned),'ожидается')}</section><section class="card">${state.income.length?state.income.slice().reverse().map(x=>row(x,`<button class="mini" data-edit="income:${x.id}">⋮</button>`)).join(''):'<div class="empty">Доходов пока нет</div>'}</section>`}
function expenses(){const t=totals();$('#main').innerHTML=`<section class="hero-head"><div><h1>Расходы</h1><p>Контроль трат без двойного учёта</p></div><button class="btn primary" data-act="expense">＋ Добавить</button></section><section class="grid two">${card('Всего расходов',money(t.expense),'учтено','red')}${card('Свободно',money(t.cash),'остаток',t.cash<0?'red':'green')}</section><section class="card">${state.expenses.length?state.expenses.slice().reverse().map(x=>row(x,`<button class="mini" data-edit="expense:${x.id}">⋮</button>`)).join(''):'<div class="empty">Расходов пока нет</div>'}</section>`}
function reserves(){const t=totals();$('#main').innerHTML=`<section class="hero-head"><div><h1>Резервы</h1><p>Подушка безопасности и финансовые цели</p></div><button class="btn primary" data-act="reserve">＋ Создать</button></section><section class="grid two">${card('Накоплено',money(t.saved),'во всех резервах','green')}${card('Цель',money(t.target),'общая цель')}</section>${state.reserves.length?state.reserves.map(r=>`<section class="card reserve"><div class="reserve-top"><div><b>${esc(r.name)}</b><small>${money(r.saved)} из ${money(r.target)}</small></div><button class="mini" data-edit="reserve:${r.id}">⋮</button></div><div class="bar"><i style="width:${r.target?Math.min(100,r.saved/r.target*100):0}%"></i></div></section>`).join(''):'<section class="card empty">Создай первую финансовую цель</section>'}`}
function shift(date){const a=new Date(state.settings.anchor+'T12:00:00'),b=new Date(date+'T12:00:00'),d=Math.round((b-a)/86400000),i=((d%6)+6)%6;return['day','day','night','night','off','off'][i]}
function calendar(){const y=month.getFullYear(),m=month.getMonth(),days=new Date(y,m+1,0).getDate(),name=month.toLocaleDateString('ru-RU',{month:'long',year:'numeric'});let html=`<section class="hero-head"><div><h1>Календарь</h1><p>${name} · график 2 дня / 2 ночи / 2 выходных</p></div><div class="actions"><button class="btn" data-month="-1">‹</button><button class="btn" data-month="1">›</button></div></section><section class="card calendar">`;for(let d=1;d<=days;d++){const iso=new Date(y,m,d).toISOString().slice(0,10),s=shift(iso),pay=s==='day'?num(state.settings.dayPay):s==='night'?num(state.settings.nightPay):0;html+=`<div class="day"><b>${d}</b><span class="shift ${s}">${s==='day'?'ДЕНЬ':s==='night'?'НОЧЬ':'ВЫХОДНОЙ'}</span>${pay?`<em>+${money(pay)}</em>`:''}</div>`}$('#main').innerHTML=html+'</section>'}
function notes(){$('#main').innerHTML=`<section class="hero-head"><div><h1>Заметки</h1><p>Личные записи приложения</p></div></section><section class="card"><textarea id="newNote" rows="4" placeholder="Напиши заметку..."></textarea><button class="btn primary" data-act="note" style="margin-top:10px">Сохранить</button></section><h3>Записи</h3>${state.notes.slice().reverse().map(n=>`<section class="card note"><div>${esc(n.text)}</div><small>${esc(n.date)}</small></section>`).join('')||'<section class="card empty">Заметок пока нет</section>'}`}
function modal(title,body,saveAction){$('#modal').innerHTML=`<div class="modal-bg"><form class="modal" onsubmit="event.preventDefault();${saveAction}"><div class="modal-title"><b>${title}</b><button type="button" class="mini" data-close>×</button></div>${body}<div class="modal-actions"><button type="button" class="btn" data-close>Отмена</button><button class="btn primary">Сохранить</button></div></form></div>`}
const field=(label,id,type='text',value='',placeholder='')=>`<label class="field">${label}<input id="${id}" type="${type}" value="${esc(value)}" placeholder="${esc(placeholder)}" ${type==='number'?'inputmode="decimal"':''}></label>`;
function openIncome(existing=null){modal(existing?'Изменить доход':'Новый доход',field('Название','fTitle','text',existing?.title,'Зарплата, подработка...')+field('Сумма','fAmount','number',existing?.amount)+field('Дата','fDate','date',existing?.date||today())+`<label class="field">Статус<select id="fStatus"><option value="actual" ${existing?.status!=='planned'?'selected':''}>Получено</option><option value="planned" ${existing?.status==='planned'?'selected':''}>Планируется</option></select></label>`,`saveIncome('${existing?.id||''}')`)}
function saveIncome(edit){const x={id:edit||id(),title:$('#fTitle').value.trim()||'Доход',amount:num($('#fAmount').value),date:$('#fDate').value,status:$('#fStatus').value};if(!x.amount)return;const i=state.income.findIndex(a=>a.id===x.id);i<0?state.income.push(x):state.income[i]=x;save();close();render()}
function openExpense(existing=null){modal(existing?'Изменить расход':'Новый расход',field('Название','fTitle','text',existing?.title,'Продукты, транспорт...')+field('Сумма','fAmount','number',existing?.amount)+field('Дата','fDate','date',existing?.date||today())+`<label class="check"><input id="fMandatory" type="checkbox" ${existing?.mandatory?'checked':''}> Обязательный расход</label>`,`saveExpense('${existing?.id||''}')`)}
function saveExpense(edit){const x={id:edit||id(),title:$('#fTitle').value.trim()||'Расход',amount:num($('#fAmount').value),date:$('#fDate').value,mandatory:$('#fMandatory').checked};if(!x.amount)return;const i=state.expenses.findIndex(a=>a.id===x.id);i<0?state.expenses.push(x):state.expenses[i]=x;save();close();render()}
function openReserve(existing=null){modal(existing?'Изменить резерв':'Новый резерв',field('Название цели','fName','text',existing?.name,'Подушка безопасности')+field('Целевая сумма','fTarget','number',existing?.target)+field('Уже накоплено','fSaved','number',existing?.saved||0),`saveReserve('${existing?.id||''}')`)}
function saveReserve(edit){const x={id:edit||id(),name:$('#fName').value.trim()||'Резерв',target:num($('#fTarget').value),saved:num($('#fSaved').value)};if(!x.target)return;const i=state.reserves.findIndex(a=>a.id===x.id);i<0?state.reserves.push(x):state.reserves[i]=x;save();close();render()}
function openDebt(){modal('Новый долг',field('Кому / за что','fName')+field('Сумма','fAmount','number')+field('Уже выплачено','fPaid','number',0)+field('Срок','fDate','date',today()),'saveDebt()')}
function saveDebt(){const x={id:id(),name:$('#fName').value.trim()||'Долг',amount:num($('#fAmount').value),paid:num($('#fPaid').value),dueDate:$('#fDate').value};if(!x.amount)return;state.debts.push(x);save();close();render()}
function close(){const m=$('#modal');if(m)m.innerHTML=''}
function bind(){document.querySelectorAll('[data-screen]').forEach(b=>b.onclick=()=>{screen=b.dataset.screen;render()});document.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>act(b.dataset.act));document.querySelectorAll('[data-edit]').forEach(b=>{b.onclick=()=>{const [type,key]=b.dataset.edit.split(':');const x=state[type==='income'?'income':type==='expense'?'expenses':'reserves'].find(v=>v.id===key);if(type==='income')openIncome(x);if(type==='expense')openExpense(x);if(type==='reserve')openReserve(x)}});document.querySelectorAll('[data-close]').forEach(b=>b.onclick=close);document.querySelectorAll('[data-month]').forEach(b=>b.onclick=()=>{month.setMonth(month.getMonth()+Number(b.dataset.month));render()});const fi=$('#importFile');if(fi)fi.onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader;r.onload=()=>{try{state=normalize(JSON.parse(r.result));save();render()}catch{alert('Файл резервной копии повреждён')}};r.readAsText(f)};}
function act(a){if(a==='menu')$('#fabMenu').classList.toggle('open');if(a==='income'){openIncome();$('#fabMenu')?.classList.remove('open')}if(a==='expense'){openExpense();$('#fabMenu')?.classList.remove('open')}if(a==='reserve'){openReserve();$('#fabMenu')?.classList.remove('open')}if(a==='debt'){openDebt();$('#fabMenu')?.classList.remove('open')}if(a==='note'){const text=$('#newNote').value.trim();if(text){state.notes.push({id:id(),text,date:new Date().toLocaleString('ru-RU')});save();render()}}if(a==='export'){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),ael=document.createElement('a');ael.href=url;ael.download='kopeyka-backup.json';ael.click();setTimeout(()=>URL.revokeObjectURL(url),500)}if(a==='import')$('#importFile').click()}
render();
})();